import os
from sys import platform

Import("env bin_DIR")

env = env.Clone()
env.SConscript("#libjp4/SConscript.externals")

env.Append(CPPPATH=["#"])
env.Append(LIBPATH=["#libjp4"])

env.MergeFlags("-Wall -Wextra")

if platform == "linux2":
	env.MergeFlags("-Wl,-rpath=%s" % env.Dir("#libjp4").abspath)

jp4_convert = env.Program("jp4-convert", source=["jp4-convert.cpp"], LIBS=["libjp4"])
jp4_info = env.Program("jp4-info", source=["jp4-info.cpp"], LIBS=["libjp4"])

# installation
env.Install(bin_DIR, jp4_convert)
env.Install(bin_DIR, jp4_info)

env.Alias("install", bin_DIR)
